'''
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

Created by: Om Chabra
Created on: 17 March 2023
@desc
    This model represents data storage with a queue of a set size. 
    It contains APIs to insert and retrieve data.  
'''
import queue

import numpy as np

from src.models.imodel import IModel, EModelTag
from src.nodes.inode import INode
from src.simlogging.ilogger import ELogType, ILogger
from src.utils import Time

class ModelDataStore(IModel):

    __modeltag = EModelTag.DATASTORE
    __ownernode: INode
    __supportednodeclasses = []
    __dependencies = []  
    __logger: ILogger

    @property
    def iName(self) -> str:
        """
        @type 
            str
        @desc
            A string representing the name of the model class. For example, ModelPower 
            Note that the name should exactly match to your class name. 
        """
        return self.__class__.__name__
    
    @property
    def modelTag(self) -> EModelTag:
        """
        @type
            EModelTag
        @desc
            The model tag for the implemented model
        """
        return self.__modeltag

    @property
    def ownerNode(self):
        """
        @type
            INode
        @desc
            Instance of the owner node that incorporates this model instance.
            The subclass (implementing a model) should keep a private variable holding the owner node instance. 
            This method can return that variable.
        """
        return self.__ownernode
    
    @property
    def supportedNodeClasses(self) -> 'list[str]':
        '''
        @type
            List of string
        @desc
            A model may not support all the node implementation. 
            supportedNodeClasses gives the list of names of the node implementation classes that it supports.
            For example, if a model supports only the SatBasic and SatAdvanced, the list should be ['SatBasic', 'SatAdvanced']
            If the model supports all the node implementations, just keep the list EMPTY.
        '''
        return self.__supportednodeclasses
    
    @property
    def dependencyModelClasses(self) -> 'list[list[str]]':
        '''
        @type
            Nested list of string
        @desc
            dependencyModelClasses gives the nested list of name of the model implementations that this model has dependency on.
            For example, if a model has dependency on the ModelPower and ModelOrbitalBasic, the list should be [['ModelPower'], ['ModelOrbitalBasic']].
            Now, if the model can work with EITHER of the ModelOrbitalBasic OR ModelOrbitalAdvanced, the these two should come under one sublist looking like [['ModelPower'], ['ModelOrbitalBasic', 'ModelOrbitalAdvanced']]. 
            So each exclusively dependent model should be in a separate sublist and all the models that can work with either of the dependent models should be in the same sublist.
            If your model does not have any dependency, just keep the list EMPTY. 
        '''
        return self.__dependencies
    
    def __str__(self) -> str:
        return "".join(["Model name: ", self.iName, ", " , "Model tag: ", self.__modeltag.__str__()])
    
    def __get_Data(self, **_kwargs):
        '''
        @desc
            This method returns the data generated by the model
        @param[in] _kwargs
            Keyworded arguments
            None 
        @return
            Data if available, None otherwise
        '''
        _retData = None
        if not self.__queue.empty():
            _retData = self.__queue.get()
            self.__log_Message(_retData, "Dequeue")
                
        return _retData
    
    def __get_Queue(self, **_kwargs):
        """
        @desc
            This method returns the data queue of the model
        @param[in] _kwargs
            Keyworded arguments
            None
        @return
            Data queue
        """
        return self.__queue
    
    def __get_QueueSize(self, **_kwargs):
        """
        @desc
            This method returns the size of the data queue of the model
        @param[in] _kwargs
            Keyworded arguments
            None
        @return
            Size of the data queue
        """
        return self.__queue.qsize()      
    
    def __add_Data(self, **_kwargs):
        """
        @desc
            This method adds data to the data queue of the model
        @param[in] _kwargs
            Keyworded arguments
            @key _data
                Data to be added to the queue
        @return
            True if data is added successfully, False otherwise
        """                
        _ret = False

        if "_data" not in _kwargs:
            raise Exception("Missing keyword argument '_data'")
        
        _data = _kwargs["_data"]
                
        if self.__queue.full():
            self.__log_Message(_data, "Dropping")
            _ret = False
        else:
            self.__log_Message(_data, "Queuing")
            self.__queue.put(_data)
            _ret = True
        
        #Let's log the queue size just when the size is changed
        self.__logger.write_Log(f"Current queue size: {self.__get_QueueSize()}", ELogType.LOGINFO, self.__ownernode.timestamp, self.iName)
        return _ret
        
    # API dictionary where API name is the key and handler function is the value
    __apiHandlerDictionary = {
        "get_Data": __get_Data,
        "get_Queue": __get_Queue,
        "get_QueueSize": __get_QueueSize,
        "add_Data": __add_Data
    }
    
    def call_APIs(
            self, 
            _apiName: str, 
            **_kwargs):
        '''
        This method acts as an API interface of the model. 
        An API offered by the model can be invoked through this method.
        @param[in] _apiName
            Name of the API. Each model should have a list of the API names.
        @param[in]  _kwargs
            Keyworded arguments that are passed to the corresponding API handler
        @return
            The API return
        This model does not have any API. So, this method does nothing.
        '''
        _ret = None

        try:
            _ret = self.__apiHandlerDictionary[_apiName](self, **_kwargs)
        except Exception as e:
            print(f"[ModelDataStore]: An unhandled API request has been received by {self.__ownernode.nodeID}:", e)
        
        return _ret
    
    def __log_Message(self, _data: 'GenericData', _event: 'str'):
        """
        @desc
            This method logs a message for the given
        @param[in] _data
            Data to be logged
        @param[in] _event
            Event to be logged 
        """
        self.__logger.write_Log(_event + f" dataID: {_data.id}. creationTime: {_data.creationTime}. sourceNodeID: {_data.sourceNodeID}." +
            f" timeDelay: {Time.difference_in_seconds(self.__ownernode.timestamp, _data.creationTime)}." +
            f" queueSize: {self.__get_QueueSize()}" \
            , ELogType.LOGINFO, self.__ownernode.timestamp, self.iName)

    def Execute(self):
        pass
    
    def __init__(
            self, 
            _ownernodeins: INode, 
            _loggerins: ILogger,
            _queueSize: int,
            ) -> None:
        '''
        @desc
            Constructor of the class
        @param[in]  _ownernodeins
            Instance of the owner node that incorporates this model instance
        @param[in]  _loggerins
            Logger instance
        '''
        self.__ownernode = _ownernodeins
        self.__logger = _loggerins
        self.__queue = queue.Queue(_queueSize)
        
def init_ModelDataStore(
    _ownernodeins: INode, 
    _loggerins: ILogger, 
    _modelArgs) -> IModel:
    '''
    @desc
        This method initializes an instance of ModelHelperFoV class
    @param[in]  _ownernodeins
        Instance of the owner node that incorporates this model instance
    @param[in]  _loggerins
        Logger instance
    @param[in]  _modelArgs
        It's a converted JSON object containing the model related info. 
        @key queue_size
            Size of the queue
    @return
        Instance of the model class
    '''
    
    assert _ownernodeins is not None
    assert _loggerins is not None
    assert _modelArgs is not None
    
    _queueSize = -1
    if 'queue_size' in _modelArgs:
        _queueSize = _modelArgs.queue_size
    
    return ModelDataStore(
                        _ownernodeins, 
                        _loggerins,
                        _queueSize)
