'''
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

Created by: Om Chabra
Created on: 14 Jul 2023
@desc
    This module analyzes the logs generated by the LoraRadioDevice and generates a table that describes the reception of packets in the specified format:

    1. frameID
    2. collision
    3. collisionFrameIDs
    4. plrDrop
    5. perDrop
    6. txBusyDrop
    7. crbwDrop
    8. nodeID
    9. timestamp
    It processes both of the following log messages:
    "Receiving. frameID: {int}. success: {bool}. collision: {bool}. collisionFrameIDs: {listOfInts}. plrDrop: {bool}. perDrop: {bool}. txBusyDrop: {bool}. crbwDrop: {bool}"
    (Note: The brackets in the log message are placeholders to indicate the actual values that will replace them.)
'''

from src.analytics.smas.isma import ISMA
import dask.dataframe as dd
from pandas import DataFrame

class SMALoraRadioDeviceRx(ISMA):
    __supportedSMANames = [] # No dependency on any other SMA
    __supportedModelNames = ['LoraRadioDevice'] # Dependency on the class in this case. 
    
    @property
    def iName(self) -> str:
        """
        @type 
            str
        @desc
            A string representing the name of the SMA class. For example, smapower 
            Note that the name should exactly match to your class name. 
        """
        return self.__class__.__name__

    @property
    def supportedModelNames(self) -> 'list[str]':
        '''
        @type
            String
        @desc
           supportedModelNames gives the list of name of the models, the log of which this SMA can process.
        '''
        return self.__supportedModelNames
    
    @property
    def supportedSMANames(self) -> 'list[str]':
        '''
        @type
            String
        @desc
            supportedSMANames gives the list of name of the SMAs, the output of which this SMA can process.
        '''
        return self.__supportedSMANames

    def call_APIs(
            self, 
            _apiName: str, 
            **_kwargs):
        '''
        This method acts as an API interface of the SMA. 
        An API offered by the SMA can be invoked through this method.
        @param[in] _apiName
            Name of the API. Each SMA should have a list of the API names.
        @param[in]  _kwargs
            Keyworded arguments that are passed to the corresponding API handler
        @return
            The API return
        '''
        pass

    def Execute(self):
        """
        This method executes the tasks that needed to be performed by the SMA.
        """
        #let's read the whole log file. Let's use dask because this log file might be huge
        _logData = dd.read_csv(self.__logFile, quotechar='"', delimiter=',', skipinitialspace=True)
        
        #we should have the following columns: logLevel, timestamp, modelName, message
        #We only need the ones where modelName matches our dependencyModelName
        _modelLogData = _logData[_logData['modelName'] == "LoraRadioDevice"]
        
        #I'm going to create two regexes & dataframes. One for the receiving log message and one for the transmitting log message
        #This is regex for a list of floats. It also includes scientific notation. g is the name of the column
        _word = lambda g: "(?P<" + g + ">[\w]+)"
        _listOfInts = lambda g: r'\[(?P<' + g+ r'>[\d, ]*)\]'
        _listOfFloats = lambda g: "\[(?P<" + g + '>[-+]?\d+(?:\.\d+)?(?:e[-+]?\d+)?(?:,\s*[-+]?\d+(?:\.\d+)?(?:e[-+]?\d+)?)*)\]'
        
        #This is all one line. I'm going to break it up into multiple lines for readability        
        _rxRegex = f"Receiving\. " + \
            "frameID: {}. ".format(_word('frameID'))  + \
            "success: {}. ".format(_word('success')) + \
            "collision: {}. ".format(_word('collision')) + \
            "collisionFrameIDs: {}. ".format(_listOfInts('collisionFrameIDs')) + \
            "plrDrop: {}. ".format(_word('plrDrop')) + \
            "perDrop: {}. ".format(_word('perDrop')) + \
            "txBusyDrop: {}. ".format(_word('txBusyDrop')) + \
            "crbwDrop: {}. ".format(_word('crbwDrop'))

        _rxInfo = _modelLogData['message'].str.extract(_rxRegex)
        #Let's add in the timestamp and the nodeID. Same reason as above
        _rxInfo['timestamp'] = _modelLogData['timestamp']
        _rxInfo['nodeID'] = self.__nodeID
        
        #drop the rows which the regex didn't match
        _rxInfo = _rxInfo.dropna()
        
        #Let's convert it to a pandas dataframe
        #Let's hope that the data is small enough to fit into memory
        _df = _rxInfo.compute()
        
        #Make all the bools into actual bools
        _boolKeys = ['success', 'collision', 'plrDrop', 'perDrop', 'txBusyDrop', 'crbwDrop']
        for _key in _boolKeys:
            _df[_key] = _df[_key].map({'True': True, 'False': False})
        
        #Make the collisionFrameIDs into a list of ints
        _df['collisionFrameIDs'] = _df['collisionFrameIDs'].str.split(',').apply(lambda x: [int(i) for i in x if i != ''])

        #Let's now make everything to the right types
        _dataTypes = {
            'frameID': 'int64',
            'timestamp': 'datetime64[ns]',
            'nodeID': 'int64',
            'success': 'bool',
            'collision': 'bool',
            'collisionFrameIDs': 'object',
            'plrDrop': 'bool',
            'perDrop': 'bool',
            'txBusyDrop': 'bool',
            'crbwDrop': 'bool'
        }
        #Let's now convert the types. Ignore any NaNs
        _df = _df.astype(_dataTypes)
        
        #Also, reset the index
        _results = _df.reset_index(drop=True)
        
        self.__results = _results

    def get_Results(self) -> DataFrame:
        '''
        @desc
            This method returns the results of the SMA in the form of a DataFrame table once it is executed.
        @return
            A DataFrame table containing the results of the SMA.
        '''
        return self.__results

    def __init__(self,
                 _modelLogPath: str):
        '''
        @desc
            Constructor
        @param[in] _modelLogPath
            Path to the log file of the model
        '''
        self.__logFile = _modelLogPath
        self.__nodeID = self.__logFile.split('/')[-1].split('_')[-1].split('.')[0] #get the nodeID from the log file name
        self.__results = None

def init_SMALoraRadioDeviceRx(**_kwargs) -> ISMA:
    '''
    @desc
        Initializes the SMALoraRadioDevice class
    @param[in] _kwargs
        Keyworded arguments that are passed to the constructor of the SMALoraRadioDevice class.
        It should have the following (key, value) pairs:
        @key modelLogPath
            Path to the log file of the model
    @return
        An instance of the SMALoraRadioDevice class
    '''
    if 'modelLogPath' not in _kwargs:
        raise Exception('[Simulator Exception] The keyworded argument modelLogPath is missing')
    
    #create an instance of the SMADataGenerator class
    _sma = SMALoraRadioDeviceRx(_kwargs['modelLogPath'])
    return _sma
